/* liste des constantes du jeu */

#ifndef CONSTANTES
#define CONSTANTES

#define TAILLE_BLOC 20
#define LIMIT_MIN_X TAILLE_BLOC*10
#define LIMIT_MIN_Y TAILLE_BLOC*8
#define LIMIT_W TAILLE_BLOC*20
#define LIMIT_H TAILLE_BLOC*10
#define NB_BLOC_HAUTEUR 28
#define NB_BLOC_LARGEUR 48
#define LARGEUR_ECRAN NB_BLOC_LARGEUR*TAILLE_BLOC
#define HAUTEUR_ECRAN NB_BLOC_HAUTEUR*TAILLE_BLOC
#define NB_BLOC_LARGEUR_TOTAL  NB_BLOC_LARGEUR*8
#define NB_BLOC_HAUTEUR_TOTAL NB_BLOC_HAUTEUR*2
#define TAILLE_ECRAN_W LARGEUR_ECRAN
#define TAILLE_ECRAN_H (NB_BLOC_HAUTEUR+5)*TAILLE_BLOC
#define NB_MUSIC 33
#define NB_SON 9
#define TEMPS_MAX 5
#define COLOR_MAX 255
#define NB_BLOC_ECRAN_GAUCHE 15
#define NB_BLOC_ECRAN_DROIT 15
#define NB_BLOC_ECRAN_MILLIEU 10
#define PT_PIECE 10
#define PT_BANDIT 20
#define PT_NIVEAU 100
#define HAUTEUR_LECTEUR 400
#define LARGEUR_LECTEUR 760
#define TEMPS_JEU_MAX 10
#define LEVEL1 6
#define LEVEL2 8
#define LEVEL3 10

enum{D1,D2,D3,G1,G2,G3};
enum{VIDE,PORTE,MUR,NUAGE,MARIO,SOL,BRIQUE,HERBE,BONUS,BONUS_OK,PIECE,ETOILE,BANDIT_1,PIQUANT,
SUIVEUR,CANON1,CANON2,SAUTEUR,PONDEUR,FLEUR,PASSEUR,GAZON1,GAZON2,GAZON3,GAZON11,GAZON22,
GAZON33,TERRE,TORTUE,BOSS1,PASSEUR1,CASSABLE,PIQUANT1,BOSS2,CANARD,DINAU,BOULET,CHAMPIGNON,VIE,FEU};
enum{SON1,SON2,SON3,SON4,SON5,SON6,SON7,SON8,SON9,SON10,SON11,SON12,SON13,SON14,SON15,SON16,SON17};
enum{GAUCHE,HAUT,DROITE,BAS};
enum{MORT,PETIT,GRAND,GEANT,SUPER};
enum{FAIBLE,NORMAL,DIFFICILE};

#endif
